/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1_vd25_202200147;

import analisis.parser;
import analisis.scanner;
import Simbolo.Arbol;
import Simbolo.tablaSimbolos;
import abstracto.Instruccion;
import excepciones.Errores;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.StringReader;
import java.util.LinkedList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

import analisis.Reportes;

/**
 *
 * @author balam
 */
public class Principal extends javax.swing.JFrame {

    private Simbolo.Arbol arbolGlobal;
    private Simbolo.tablaSimbolos tablaGlobal;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        btnEjecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenidoEntrada = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        txtruta = new javax.swing.JTextField();
        btnAbrirArchivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerarReportes = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 850));
        getContentPane().setLayout(null);

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setLayout(new javax.swing.OverlayLayout(panel1));
        getContentPane().add(panel1);
        panel1.setBounds(0, 813, 802, 0);
        panel1.getAccessibleContext().setAccessibleDescription("");

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjecutar);
        btnEjecutar.setBounds(590, 30, 75, 25);

        txtContenidoEntrada.setColumns(20);
        txtContenidoEntrada.setRows(5);
        jScrollPane1.setViewportView(txtContenidoEntrada);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 370, 450);

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane3.setViewportView(txtConsola);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(420, 100, 400, 450);

        txtruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrutaActionPerformed(evt);
            }
        });
        getContentPane().add(txtruta);
        txtruta.setBounds(50, 30, 390, 30);

        btnAbrirArchivo.setText("Abrir Archivo");
        btnAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirArchivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAbrirArchivo);
        btnAbrirArchivo.setBounds(450, 30, 120, 25);

        jLabel2.setText("CONSOLA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 80, 80, 16);

        jLabel3.setText("ENTRADA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 70, 16);

        btnGenerarReportes.setText("Generar Reportes");
        btnGenerarReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReportes);
        btnGenerarReportes.setBounds(670, 30, 140, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        
        String entrada = txtContenidoEntrada.getText();

        try {
            scanner s = new scanner(new StringReader(entrada));
            parser p = new parser(s);

            // Ejecutar análisis (Ahora con recuperación de errores gracias al CUP modificado)
            var resultado = p.parse();

            // 1. Inicializar Arbol y Tabla Globales
            LinkedList<Instruccion> ast = (LinkedList<Instruccion>) resultado.value;
            this.tablaGlobal = new tablaSimbolos(null);
            this.tablaGlobal.setNombre("GLOBAL");

            // Si el parser devolvió null (fallo total), inicializamos lista vacía
            if (ast == null) ast = new LinkedList<>();

            this.arbolGlobal = new Arbol(ast);

            // 2. Agregar errores de compilación detectados (Léxicos/Sintácticos) al reporte
            this.arbolGlobal.errores.addAll(s.listaErrores);
            this.arbolGlobal.errores.addAll(p.listaErrores);

            // 3. EJECUTAR EL AST (Incluso si hubo errores sintácticos previos)
            //    Esto permitirá que se guarden las variables válidas antes del error.

            txtConsola.setText(""); // Limpiar consola

            for (Instruccion ins : ast) {
                // IMPORTANTE: Como agregamos "error" en el CUP que retorna null,
                // debemos validar que la instrucción no sea null antes de ejecutarla.
                if (ins == null) continue; 

                var res = ins.interpretar(this.arbolGlobal, this.tablaGlobal);

                if (res instanceof Errores) {
                    this.arbolGlobal.errores.add((Errores) res);
                }
            }

            // 4. Mostrar Salidas
            txtConsola.setText(this.arbolGlobal.getConsolas());

            // 5. Mostrar Reporte de Errores en la consola de la GUI
            if (!this.arbolGlobal.errores.isEmpty()) {
                txtConsola.append("\n--- SE ENCONTRARON ERRORES ---\n");
                for (Errores err : this.arbolGlobal.errores) {
                    txtConsola.append(err.toString() + "\n");
                }
            }

        } catch (Exception ex) {
            txtConsola.setText("Error fatal: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void txtrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrutaActionPerformed

    private void btnAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirArchivoActionPerformed
        // TODO add your handling code here:
        // Configurar el selector de archivos
        JFileChooser selector = new JFileChooser();
        
        selector.setFileFilter(new FileNameExtensionFilter("Archivos JavaUSAC (.ju, .jc)", "ju", "jc"));

        int resultado = selector.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = selector.getSelectedFile();

            // Mostrar la ruta en el campo de texto
            txtruta.setText(archivoSeleccionado.getAbsolutePath());

            try (BufferedReader reader = new BufferedReader(new FileReader(archivoSeleccionado))) {
                String linea;
                StringBuilder contenido = new StringBuilder();

                while ((linea = reader.readLine()) != null) {
                    contenido.append(linea).append("\n");
                }

                // Mostrar el contenido en el área de texto superior (Editor)
                txtContenidoEntrada.setText(contenido.toString());

                // Limpiar la consola anterior
                txtConsola.setText(""); 

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAbrirArchivoActionPerformed

    private void btnGenerarReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportesActionPerformed
                     // TODO add your handling code here:
       if (this.arbolGlobal != null && this.tablaGlobal != null) {
            // 1. Reporte de Errores (Semánticos + los que guardaste de sintaxis si los pasaste)
            Reportes.generarReporteErrores(this.arbolGlobal.errores);

            // 2. Reporte de Tabla de Símbolos (Variables Globales)
            Reportes.generarReporteSimbolos(this.tablaGlobal.getVariables());

            javax.swing.JOptionPane.showMessageDialog(this, "¡Reportes HTML generados en la carpeta del proyecto!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debes ejecutar el código.");
        }
    }//GEN-LAST:event_btnGenerarReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbrirArchivo;
    public javax.swing.JButton btnEjecutar;
    public javax.swing.JButton btnGenerarReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Panel panel1;
    public javax.swing.JTextArea txtConsola;
    public javax.swing.JTextArea txtContenidoEntrada;
    public javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
